### ISSUE TITLE
Access Violation error on startup

### ISSUE THREAD

**Issue by luigino** [varianus/ovoplayer#4]
Ovoplayer launches, but I see a number of errors on console and closing it
from the window gadget is not always possible. (see [attachment](https://github.com/varianus/ovoplayer/files/1568076/ovo.log)).

ovoplayer 1.3, lazarus 1.8.0, fpc 3.0.4

**Comment by varianus** [comment]
Where did you download sources?

Your log say: 
`ovoplayer v1.4.0 Rev. 753M`
V1.4.0 is the current trunk and revision 753 is quite old.

The SVN repository for branch 1.3 is avalaible at this address: [https://sourceforge.net/p/ovoplayer/code/HEAD/tree/branches/1.3/](https://sourceforge.net/p/ovoplayer/code/HEAD/tree/branches/1.3/
)

If you prefer downloading an updated tarball : [https://sourceforge.net/code-snapshots/svn/o/ov/ovoplayer/code/ovoplayer-code-797-branches-1.3.zip](https://sourceforge.net/code-snapshots/svn/o/ov/ovoplayer/code/ovoplayer-code-797-branches-1.3.zip)

**Comment by luigino** [comment]
> Where did you download sources?

I used the latest github release.

> Your log say:
> ovoplayer v1.4.0 Rev. 753M
> V1.4.0 is the current trunk and revision 753 is quite old.

> The SVN repository for branch 1.3 is avalaible at this address: https://sourceforge.net/p/ovoplayer/code/HEAD/tree/branches/1.3/

[ovoplayer_svn797.txt](https://github.com/varianus/ovoplayer/files/1572852/ovoplayer_svn797.txt)


> If you prefer downloading an updated tarball : https://sourceforge.net/code-snapshots/svn/o/ov/ovoplayer/code/ovoplayer-code-797-branches-1.3.zip

[ovoplayer_snapshot_797.txt](https://github.com/varianus/ovoplayer/files/1572854/ovoplayer_snapshot_797.txt)

No change, I'm afraid.

**Comment by varianus** [comment]
The error seems to be related to the initialization of the audio engine or database.
Unfortunately I can not understand exactly where the error comes from using your stacktrace.
Could you please build with debug info enabled? It would be very helpful to locate errors.
You can use the **buildlinux_dbg.sh** script for this.
Thanks.

**Comment by luigino** [comment]
```
=============================================
| 20-12-2017, 18:41:37
| ovoplayer v1.4.0 Rev. 770M
| TApplication.HandleException EAccessViolation Access violation
  Stack trace:
  $0000000000000000
  $0000000000762559 line 3825 of grids.pas
  $00000000007781CB line 10222 of grids.pas
  $0000000000763D44 line 4227 of grids.pas
  $0000000000763A65 line 4252 of grids.pas
  $0000000000763820 line 4181 of grids.pas
  $000000000076203D line 3749 of grids.pas
  $0000000000678F10 line 132 of include/customcontrol.inc
  $000000000066055C line 4819 of include/wincontrol.inc
  $00000000006648D3 line 6772 of include/wincontrol.inc
  $0000000000678E46 line 112 of include/customcontrol.inc
  $000000000043A11F
  $0000000000661A9C line 5396 of include/wincontrol.inc
  $0000000000765252 line 4708 of grids.pas
  $00000000006EC674 line 4169 of qt5/qtwidgets.pas
  $00000000006E9876 line 2690 of qt5/qtwidgets.pas
  $000000000070A568 line 16982 of qt5/qtwidgets.pas
```
Hope this helps!

**Comment by varianus** [comment]
The error seem related to QT5 widgets. I've never tried a QT5 build (QT4 works fine) because Lazarus's QT5 bindings are for QT5 5.6.1, last revision available on my Xubuntu 16.04 is 5.5.1. I'll try to setup a build enviroment on a virtual machine when i come back from vacation.

**Comment by varianus** [comment]
I've finally managed to setup an OpenSUSE virtual machine. There was an initialization error  of tray icon for QT5. Another error during audio engine availability check generated the closing problem. Now they should be fixed on trunk and on 1.3 branch.

**Comment by luigino** [comment]
Much better, but it still hangs on exit when closed from the gadget.
(no problem with File/Quit)

**Comment by varianus** [comment]
I've tried a lot of times, also with a GTK build and i can't replicate the issue. Do you have some error on console when it hangs?

**Comment by luigino** [comment]
None whatsoever.
Brass tacks, this is how I build it:
```
cp debug.cfg extrafpc.cfg
lazbuild -B -r --build-mode=Release src/components/mcaselli.lpk
lazbuild -B -r --build-mode=Release --widgetset=qt5 src/ovoplayer.lpi
```

The shell just hangs. I've tried with qt5 and gtk2.
